CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE listings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(10),
  title VARCHAR(255),
  price DECIMAL(10,2),
  book_condition VARCHAR(50),
  pickup VARCHAR(100),
  seller VARCHAR(15),
  image VARCHAR(255)
);